version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: '04:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '04:30'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
