import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ExcelJS, { type CellValue, type Row, type Worksheet } from 'exceljs';

const SCRIPT_DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC_SAMPLES_DIRECTORY = path.resolve(SCRIPT_DIRECTORY, '../public/samples');
const FIXED_TIMESTAMP = new Date('2026-01-01T00:00:00.000Z');
const FIXED_DOS_TIME = 0;
const FIXED_DOS_DATE = ((FIXED_TIMESTAMP.getUTCFullYear() - 1980) << 9) | (1 << 5) | 1;

const HEADERS_ZH = [
  '序号',
  '项目编码',
  '项目名称',
  '项目特征',
  '计量单位',
  '工程量',
  '综合单价',
  '合价',
  '备注',
] as const;

const HEADERS_EN = [
  'No.',
  'Item Code',
  'Item Name',
  'Item Feature',
  'Unit',
  'Quantity',
  'Unit Price',
  'Total Price',
  'Remarks',
] as const;

const COLORS = {
  navy: '1F3349',
  paleOrange: 'FFF3E0',
  border: 'C8D1DC',
  white: 'FFFFFF',
  text: '17212B',
  muted: '5D6B79',
} as const;

type SampleRow = readonly CellValue[];

function createWorkbook(title: string): ExcelJS.Workbook {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'BOQLint';
  workbook.lastModifiedBy = 'BOQLint';
  workbook.created = FIXED_TIMESTAMP;
  workbook.modified = FIXED_TIMESTAMP;
  workbook.title = title;
  workbook.subject = title;
  workbook.description =
    'Entirely fictional demonstration data generated by BOQLint. No real project, company, or market price data.';
  workbook.company = 'BOQLint Open Source Project';
  return workbook;
}

function styleHeader(row: Row): void {
  row.height = 30;
  row.eachCell({ includeEmpty: true }, (cell) => {
    cell.font = { bold: true, color: { argb: COLORS.white }, name: 'Arial', size: 10 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.navy } };
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
    cell.border = {
      top: { style: 'thin', color: { argb: COLORS.navy } },
      bottom: { style: 'thin', color: { argb: COLORS.navy } },
    };
  });
}

function styleDataRow(row: Row): void {
  row.height = 26;
  row.font = { color: { argb: COLORS.text }, name: 'Arial', size: 10 };
  row.alignment = { vertical: 'middle', wrapText: true };
  row.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
  row.getCell(2).numFmt = '@';
  row.getCell(5).alignment = { horizontal: 'center', vertical: 'middle' };
  row.getCell(6).numFmt = '#,##0.000';
  row.getCell(7).numFmt = '#,##0.00';
  row.getCell(8).numFmt = '#,##0.00';
  row.eachCell({ includeEmpty: true }, (cell) => {
    cell.border = { bottom: { style: 'hair', color: { argb: COLORS.border } } };
  });
}

function prepareSheet(
  workbook: ExcelJS.Workbook,
  name: string,
  title: string,
  note: string,
  headers: readonly string[],
): Worksheet {
  const worksheet = workbook.addWorksheet(name, {
    properties: { defaultRowHeight: 20 },
    views: [{ state: 'frozen', ySplit: 4, activeCell: 'A5', showGridLines: false }],
    pageSetup: {
      paperSize: 9,
      orientation: 'landscape',
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
      margins: { left: 0.3, right: 0.3, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
    },
  });
  worksheet.pageSetup.printTitlesRow = '1:4';

  [8, 18, 24, 38, 12, 14, 15, 16, 28].forEach((width, index) => {
    worksheet.getColumn(index + 1).width = width;
  });

  worksheet.mergeCells('A1:I1');
  const titleCell = worksheet.getCell('A1');
  titleCell.value = title;
  titleCell.font = { bold: true, color: { argb: COLORS.white }, name: 'Arial', size: 16 };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.navy } };
  titleCell.alignment = { horizontal: 'left', vertical: 'middle' };
  worksheet.getRow(1).height = 34;

  worksheet.mergeCells('A2:I2');
  const noteCell = worksheet.getCell('A2');
  noteCell.value = note;
  noteCell.font = { italic: true, color: { argb: COLORS.muted }, name: 'Arial', size: 10 };
  noteCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.paleOrange } };
  noteCell.alignment = { vertical: 'middle', wrapText: true };
  worksheet.getRow(2).height = 32;

  const header = worksheet.getRow(4);
  header.values = [...headers];
  styleHeader(header);
  worksheet.autoFilter = { from: 'A4', to: 'I4' };
  return worksheet;
}

function addRows(worksheet: Worksheet, rows: readonly SampleRow[]): void {
  for (const values of rows) {
    const row = worksheet.addRow([...values]);
    styleDataRow(row);
  }
}

function createValidZhSample(): ExcelJS.Workbook {
  const workbook = createWorkbook('BOQLint 正常中文清单示例');
  const worksheet = prepareSheet(
    workbook,
    '虚构清单',
    'BOQLint 正常清单示例（虚构）',
    '完全虚构演示数据；不对应任何真实项目、公司或市场价格，仅用于测试 BOQLint。',
    HEADERS_ZH,
  );

  addRows(worksheet, [
    [
      1,
      '010101001001',
      '虚构土方演示项甲',
      '虚构参数：类别甲；仅供功能演示',
      'm³',
      12.5,
      8,
      100,
      '虚构数据',
    ],
    [
      2,
      '010101001002',
      '虚构构件演示项乙',
      '虚构参数：规格乙；仅供功能演示',
      '件',
      7.25,
      12,
      87,
      '虚构数据',
    ],
    [
      3,
      '010101001003',
      '虚构表面演示项丙',
      '虚构参数：做法丙；仅供功能演示',
      'm²',
      4,
      25,
      100,
      '虚构数据',
    ],
    [
      4,
      '010101001004',
      '虚构长度演示项丁',
      '虚构参数：尺寸丁；仅供功能演示',
      'm',
      3.2,
      15,
      48,
      '虚构数据',
    ],
    [
      5,
      '010101001005',
      '虚构体积演示项戊',
      '虚构参数：等级戊；仅供功能演示',
      'm³',
      2.5,
      18,
      45,
      '虚构数据',
    ],
    [
      6,
      '010101001006',
      '虚构数量演示项己',
      '虚构参数：型号己；仅供功能演示',
      '个',
      6,
      9.5,
      57,
      '虚构数据',
    ],
  ]);
  return workbook;
}

function createValidEnSample(): ExcelJS.Workbook {
  const workbook = createWorkbook('BOQLint valid English BOQ sample');
  const worksheet = prepareSheet(
    workbook,
    'Fictional BOQ',
    'BOQLint Valid BOQ Sample (Fictional)',
    'Entirely fictional demonstration data. It represents no real project, company, or market price.',
    HEADERS_EN,
  );

  addRows(worksheet, [
    [
      1,
      '020101001001',
      'Fictional Demo Item Alpha',
      'Fictional specification Alpha; demonstration only',
      'm³',
      10,
      7.5,
      75,
      'Fictional data',
    ],
    [
      2,
      '020101001002',
      'Fictional Demo Item Beta',
      'Fictional specification Beta; demonstration only',
      'item',
      4,
      16,
      64,
      'Fictional data',
    ],
    [
      3,
      '020101001003',
      'Fictional Demo Item Gamma',
      'Fictional specification Gamma; demonstration only',
      'm²',
      8.5,
      6,
      51,
      'Fictional data',
    ],
    [
      4,
      '020101001004',
      'Fictional Demo Item Delta',
      'Fictional specification Delta; demonstration only',
      'm',
      2.4,
      25,
      60,
      'Fictional data',
    ],
    [
      5,
      '020101001005',
      'Fictional Demo Item Epsilon',
      'Fictional specification Epsilon; demonstration only',
      'set',
      3,
      18,
      54,
      'Fictional data',
    ],
  ]);
  return workbook;
}

function createIssuesZhSample(): ExcelJS.Workbook {
  const workbook = createWorkbook('BOQLint 含问题中文清单示例');
  const worksheet = prepareSheet(
    workbook,
    '含问题的虚构清单',
    'BOQLint 含问题清单示例（虚构）',
    '完全虚构演示数据；故意包含数据质量问题，不对应任何真实项目、公司或市场价格。',
    HEADERS_ZH,
  );

  addRows(worksheet, [
    [1, '030101001001', '', '虚构参数：故意缺少项目名称', 'm³', 10, 4, 40, '缺少必需字段'],
    [
      2,
      '030101001002',
      '虚构无效数字示例',
      '虚构参数：工程量故意使用文本',
      'm²',
      '十二点五',
      6,
      75,
      '无效数字',
    ],
    [3, '030101001003', '虚构零工程量示例', '虚构参数：工程量故意为零', '项', 0, 8, 0, '零工程量'],
    [
      4,
      '030101001004',
      '虚构完全重复示例',
      '虚构参数：两行内容故意完全相同',
      '根',
      2,
      15,
      30,
      '完全重复行',
    ],
    [
      4,
      '030101001004',
      '虚构完全重复示例',
      '虚构参数：两行内容故意完全相同',
      '根',
      2,
      15,
      30,
      '完全重复行',
    ],
    [
      6,
      '030101001005',
      '虚构单位冲突示例',
      '虚构参数：同编码故意使用不同单位',
      'm',
      3,
      10,
      30,
      '同编码不同单位',
    ],
    [
      7,
      '030101001005',
      '虚构单位冲突示例',
      '虚构参数：同编码故意使用不同单位',
      'm²',
      4,
      10,
      40,
      '同编码不同单位',
    ],
    [
      8,
      '030101001006',
      '虚构计算错误示例',
      '虚构参数：合价故意不等于工程量乘单价',
      '项',
      5,
      7,
      36,
      '正确合价应为 35',
    ],
    [
      9,
      '030101001007',
      '虚构公式错误示例',
      '虚构参数：合价公式故意除以零',
      '项',
      2,
      5,
      { formula: 'F13/0', result: { error: '#DIV/0!' } },
      '公式错误',
    ],
    [10, '030101001008', '虚构空特征示例', '', '个', 1, 9, 9, '项目特征为空'],
    [
      11,
      ' 030101001009 \n',
      '虚构编码空白示例',
      '虚构参数：编码故意包含首尾空白',
      '套',
      2,
      11,
      22,
      '编码首尾空白',
    ],
    [
      12,
      '030101001010',
      '虚构隐藏行示例',
      '虚构参数：该明细行被故意隐藏',
      '项',
      1,
      13,
      13,
      '隐藏行',
    ],
    [...HEADERS_ZH],
    [
      13,
      '030101001011',
      '虚构公式无缓存示例',
      '虚构参数：公式故意不含缓存结果',
      '项',
      3,
      5,
      { formula: 'F18*G18' },
      '公式无缓存结果',
    ],
    ['', '', '虚构章节标题', '', '', '', '', '', '非明细行'],
    ['', '', '虚构小计', '', '', '', '', 255, '非明细行'],
  ]);
  worksheet.getRow(16).hidden = true;
  worksheet.getRow(16).outlineLevel = 1;
  styleHeader(worksheet.getRow(17));
  worksheet.addRow([]);
  addRows(worksheet, [
    [
      14,
      '030101001012',
      '虚构尾部正常示例',
      '虚构参数：用于确认重复表头后继续读取',
      '项',
      2,
      10,
      20,
      '虚构数据',
    ],
  ]);
  return workbook;
}

function normalizeZipEntryTimestamps(buffer: Buffer): void {
  const endOfCentralDirectorySignature = 0x06054b50;
  const centralDirectorySignature = 0x02014b50;
  const localFileSignature = 0x04034b50;
  const minimumEndRecordSize = 22;
  const earliestEndRecord = Math.max(0, buffer.length - 65_535 - minimumEndRecordSize);
  let endRecordOffset = -1;

  for (
    let offset = buffer.length - minimumEndRecordSize;
    offset >= earliestEndRecord;
    offset -= 1
  ) {
    if (buffer.readUInt32LE(offset) === endOfCentralDirectorySignature) {
      endRecordOffset = offset;
      break;
    }
  }
  if (endRecordOffset < 0) throw new Error('生成的工作簿缺少 ZIP 目录记录。');

  const centralDirectorySize = buffer.readUInt32LE(endRecordOffset + 12);
  const centralDirectoryOffset = buffer.readUInt32LE(endRecordOffset + 16);
  const centralDirectoryEnd = centralDirectoryOffset + centralDirectorySize;
  let entryOffset = centralDirectoryOffset;

  while (entryOffset < centralDirectoryEnd) {
    if (buffer.readUInt32LE(entryOffset) !== centralDirectorySignature) {
      throw new Error('生成的工作簿 ZIP 目录无效。');
    }
    buffer.writeUInt16LE(FIXED_DOS_TIME, entryOffset + 12);
    buffer.writeUInt16LE(FIXED_DOS_DATE, entryOffset + 14);

    const localHeaderOffset = buffer.readUInt32LE(entryOffset + 42);
    if (buffer.readUInt32LE(localHeaderOffset) !== localFileSignature) {
      throw new Error('生成的工作簿 ZIP 本地记录无效。');
    }
    buffer.writeUInt16LE(FIXED_DOS_TIME, localHeaderOffset + 10);
    buffer.writeUInt16LE(FIXED_DOS_DATE, localHeaderOffset + 12);

    const fileNameLength = buffer.readUInt16LE(entryOffset + 28);
    const extraFieldLength = buffer.readUInt16LE(entryOffset + 30);
    const commentLength = buffer.readUInt16LE(entryOffset + 32);
    entryOffset += 46 + fileNameLength + extraFieldLength + commentLength;
  }
}

async function saveWorkbook(workbook: ExcelJS.Workbook, fileName: string): Promise<void> {
  const output = Buffer.from(
    await workbook.xlsx.writeBuffer({
      useSharedStrings: true,
      useStyles: true,
      zip: { compression: 'DEFLATE', compressionOptions: { level: 9 } },
    }),
  );
  normalizeZipEntryTimestamps(output);
  await writeFile(path.join(PUBLIC_SAMPLES_DIRECTORY, fileName), output);
}

async function main(): Promise<void> {
  await mkdir(PUBLIC_SAMPLES_DIRECTORY, { recursive: true });
  await Promise.all([
    saveWorkbook(createValidZhSample(), 'boq-valid-zh.xlsx'),
    saveWorkbook(createIssuesZhSample(), 'boq-issues-zh.xlsx'),
    saveWorkbook(createValidEnSample(), 'boq-valid-en.xlsx'),
  ]);
  console.info('Generated three public workbooks in public/samples/.');
}

await main();
