import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ExcelJS, { type CellValue, type Row, type Worksheet } from 'exceljs';

const SCRIPT_DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const EXAMPLES_DIRECTORY = path.resolve(SCRIPT_DIRECTORY, '../examples');
const PUBLIC_SAMPLES_DIRECTORY = path.resolve(SCRIPT_DIRECTORY, '../public/samples');
const FIXED_TIMESTAMP = new Date('2026-01-01T00:00:00.000Z');
const FIXED_DOS_TIME = 0;
const FIXED_DOS_DATE = ((FIXED_TIMESTAMP.getUTCFullYear() - 1980) << 9) | (1 << 5) | 1;

const HEADERS = [
  '序号',
  '项目编码',
  '项目名称',
  '项目特征',
  '计量单位',
  '工程量',
  '综合单价',
  '合价',
  '备注',
] as const;

const COLORS = {
  navy: '1F3349',
  paleOrange: 'FFF3E0',
  border: 'C8D1DC',
  white: 'FFFFFF',
  text: '17212B',
  muted: '5D6B79',
} as const;

type SampleRow = readonly CellValue[];

function createWorkbook(title: string): ExcelJS.Workbook {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'BOQ Lint';
  workbook.lastModifiedBy = 'BOQ Lint';
  workbook.created = FIXED_TIMESTAMP;
  workbook.modified = FIXED_TIMESTAMP;
  workbook.title = title;
  workbook.subject = '完全虚构的 BOQ Lint 功能演示数据';
  workbook.description =
    'Entirely fictional demonstration data generated by BOQ Lint. No real project, company, quota, or market-price data.';
  workbook.company = 'BOQ Lint Open Source Project';
  return workbook;
}

function styleHeader(row: Row): void {
  row.height = 30;
  row.eachCell({ includeEmpty: true }, (cell) => {
    cell.font = { bold: true, color: { argb: COLORS.white }, name: 'Arial', size: 10 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.navy } };
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
    cell.border = {
      top: { style: 'thin', color: { argb: COLORS.navy } },
      bottom: { style: 'thin', color: { argb: COLORS.navy } },
    };
  });
}

function styleDataRow(row: Row): void {
  row.height = 26;
  row.font = { color: { argb: COLORS.text }, name: 'Arial', size: 10 };
  row.alignment = { vertical: 'middle', wrapText: true };
  row.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
  row.getCell(2).numFmt = '@';
  row.getCell(5).alignment = { horizontal: 'center', vertical: 'middle' };
  row.getCell(6).numFmt = '#,##0.000';
  row.getCell(7).numFmt = '#,##0.00';
  row.getCell(8).numFmt = '#,##0.00';
  row.eachCell({ includeEmpty: true }, (cell) => {
    cell.border = { bottom: { style: 'hair', color: { argb: COLORS.border } } };
  });
}

function prepareSheet(
  workbook: ExcelJS.Workbook,
  name: string,
  title: string,
  note: string,
): Worksheet {
  const worksheet = workbook.addWorksheet(name, {
    properties: { defaultRowHeight: 20 },
    views: [{ state: 'frozen', ySplit: 4, activeCell: 'A5', showGridLines: false }],
    pageSetup: {
      paperSize: 9,
      orientation: 'landscape',
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
      margins: { left: 0.3, right: 0.3, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
    },
  });
  worksheet.pageSetup.printTitlesRow = '1:4';

  [8, 18, 28, 42, 12, 14, 15, 16, 28].forEach((width, index) => {
    worksheet.getColumn(index + 1).width = width;
  });

  worksheet.mergeCells('A1:I1');
  const titleCell = worksheet.getCell('A1');
  titleCell.value = title;
  titleCell.font = { bold: true, color: { argb: COLORS.white }, name: 'Arial', size: 16 };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.navy } };
  titleCell.alignment = { horizontal: 'left', vertical: 'middle' };
  worksheet.getRow(1).height = 34;

  worksheet.mergeCells('A2:I2');
  const noteCell = worksheet.getCell('A2');
  noteCell.value = note;
  noteCell.font = { italic: true, color: { argb: COLORS.muted }, name: 'Arial', size: 10 };
  noteCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.paleOrange } };
  noteCell.alignment = { vertical: 'middle', wrapText: true };
  worksheet.getRow(2).height = 32;

  const header = worksheet.getRow(4);
  header.values = [...HEADERS];
  styleHeader(header);
  worksheet.autoFilter = { from: 'A4', to: 'I4' };
  return worksheet;
}

function addRow(worksheet: Worksheet, values: SampleRow): Row {
  const row = worksheet.addRow([...values]);
  styleDataRow(row);
  return row;
}

function createCleanSample(): ExcelJS.Workbook {
  const workbook = createWorkbook('BOQ Lint 干净清单示例');
  const worksheet = prepareSheet(
    workbook,
    '干净的虚构清单',
    'BOQ Lint 干净清单示例（完全虚构）',
    '所有项目、参数和价格均为功能演示数据，不对应任何真实工程、企业模板、定额或市场价格。',
  );

  addRow(worksheet, ['', '', '分部：虚构演示清单', '', '', '', '', '', '非清单项目行']);
  [
    [
      1,
      '010101001001',
      '虚构演示项目甲',
      '虚构参数：规格甲；材质甲；仅供演示',
      'm³',
      12.5,
      8,
      100,
      '虚构数据',
    ],
    [
      2,
      '010101001002',
      '虚构演示项目乙',
      '虚构参数：规格乙；材质乙；仅供演示',
      'm²',
      7.25,
      12,
      87,
      '虚构数据',
    ],
    [
      3,
      '010101001003',
      '虚构演示项目丙',
      '虚构参数：规格丙；材质丙；仅供演示',
      'm',
      4,
      25,
      100,
      '虚构数据',
    ],
    [
      4,
      '010101001004',
      '虚构演示项目丁',
      '虚构参数：规格丁；材质丁；仅供演示',
      '项',
      3.2,
      15,
      48,
      '虚构数据',
    ],
    [
      5,
      '010101001005',
      '虚构演示项目戊',
      '虚构参数：规格戊；材质戊；仅供演示',
      '件',
      2.5,
      18,
      45,
      '虚构数据',
    ],
    [
      6,
      '010101001006',
      '虚构演示项目己',
      '虚构参数：规格己；材质己；仅供演示',
      '套',
      6,
      9.5,
      57,
      '虚构数据',
    ],
  ].forEach((row) => addRow(worksheet, row));
  addRow(worksheet, ['', '', '备注：以上全部为虚构数据', '', '', '', '', '', '非清单项目行']);
  addRow(worksheet, ['', '', '小计', '', '', '', '', 437, '非清单项目行']);
  return workbook;
}

function createRiskSample(): ExcelJS.Workbook {
  const workbook = createWorkbook('BOQ Lint 风险清单示例');
  const worksheet = prepareSheet(
    workbook,
    '含问题的虚构清单',
    'BOQ Lint 风险清单示例（完全虚构）',
    '本示例故意包含 QG001–QG014 辅助检查风险；不对应任何真实工程、企业模板、定额或市场价格。',
  );

  addRow(worksheet, ['', '', '分部：虚构风险演示', '', '', '', '', '', '章节标题']);
  addRow(worksheet, [
    1,
    '030101001001',
    '',
    '虚构参数：项目名称故意留空',
    'm²',
    1,
    10,
    10,
    '触发 QG001',
  ]);
  addRow(worksheet, [
    2,
    '030101001002',
    '虚构缺少单位项目',
    '虚构参数：计量单位故意留空',
    '',
    2,
    10,
    20,
    '触发 QG002',
  ]);
  addRow(worksheet, [
    3,
    '030101001003',
    '虚构无效工程量项目',
    '虚构参数：工程量使用不可解析文本',
    'm³',
    '数量待定',
    10,
    20,
    '触发 QG003',
  ]);
  addRow(worksheet, [
    4,
    '030101001004',
    '虚构零工程量项目',
    '虚构参数：工程量故意为零',
    '项',
    0,
    8,
    0,
    '触发 QG004',
  ]);
  addRow(worksheet, [
    5,
    '',
    '虚构缺少编码项目',
    '虚构参数：项目编码故意留空',
    'm',
    3,
    10,
    30,
    '触发 QG005',
  ]);
  addRow(worksheet, [
    6,
    'DEMO-006',
    '虚构可疑编码项目',
    '虚构参数：使用非十二位编码',
    '套',
    1,
    20,
    20,
    '触发 QG006',
  ]);
  addRow(worksheet, [
    7,
    '030101001007',
    '虚构重复编码项目甲',
    '虚构参数：重复编码第一项',
    '根',
    2,
    15,
    30,
    '触发 QG007',
  ]);
  addRow(worksheet, [
    8,
    '030101001007',
    '虚构重复编码项目乙',
    '虚构参数：重复编码第二项',
    '根',
    3,
    15,
    45,
    '触发 QG007',
  ]);
  addRow(worksheet, [
    9,
    '030101001008',
    '虚构疑似重复项目',
    '虚构参数：名称特征单位完全相同',
    '个',
    1,
    12,
    12,
    '触发 QG008',
  ]);
  addRow(worksheet, [
    10,
    '030101001009',
    '虚构疑似重复项目',
    '虚构参数：名称特征单位完全相同',
    '个',
    2,
    12,
    24,
    '触发 QG008',
  ]);
  addRow(worksheet, [11, '030101001010', '虚构短特征项目', '短', '项', 1, 9, 9, '触发 QG009']);
  addRow(worksheet, [
    12,
    '030101001011',
    '虚构占位特征项目',
    '项目特征详见图纸',
    '项',
    1,
    9,
    9,
    '触发 QG009',
  ]);
  addRow(worksheet, [
    13,
    '030101001006',
    '虚构合价错误项目',
    '虚构参数：合价故意不等于数量乘单价',
    '项',
    5,
    7,
    36,
    '触发 QG010；正确合价为 35',
  ]);
  addRow(worksheet, [
    14,
    '030101001012',
    '虚构负单价项目',
    '虚构参数：综合单价故意为负数',
    '项',
    1,
    -5,
    -5,
    '触发 QG011',
  ]);
  addRow(worksheet, [
    15,
    '030101001013',
    '虚构零单价项目',
    '虚构参数：综合单价故意为零',
    '项',
    2,
    0,
    0,
    '触发 QG011',
  ]);
  [
    ['030101001014', '虚构同类离散项目', '虚构参数：同类价格样本甲', 100],
    ['030101001015', '虚构同类离散项目', '虚构参数：同类价格样本乙', 102],
    ['030101001016', '虚构同类离散项目', '虚构参数：同类价格样本丙', 98],
    ['030101001017', '虚构同类离散项目', '虚构参数：同类价格离群项', 300],
  ].forEach(([code, name, feature, price], index) =>
    addRow(worksheet, [
      16 + index,
      code,
      name,
      feature,
      'm²',
      1,
      price,
      price,
      index === 3 ? '触发 QG012' : 'QG012 对照样本',
    ]),
  );

  const formulaRow = addRow(worksheet, [
    20,
    '030101001018',
    '虚构公式无缓存项目',
    '虚构参数：合价公式故意不保存缓存结果',
    '项',
    2,
    3,
    null,
    '触发 QG013',
  ]);
  formulaRow.getCell(8).value = {
    formula: `F${formulaRow.number}*G${formulaRow.number}`,
  };

  const hiddenRow = addRow(worksheet, [
    21,
    '030101001019',
    '虚构隐藏数据项目',
    '虚构参数：整行被故意隐藏',
    '项',
    1,
    11,
    11,
    '触发 QG014',
  ]);
  hiddenRow.hidden = true;
  hiddenRow.outlineLevel = 1;

  const mergedRow = addRow(worksheet, [
    22,
    '030101001020',
    '虚构合并字段项目',
    '',
    '项',
    1,
    13,
    13,
    '触发 QG014',
  ]);
  worksheet.mergeCells(`C${mergedRow.number}:D${mergedRow.number}`);
  worksheet.getColumn(1).hidden = true;
  addRow(worksheet, ['', '', '备注：本表问题均为故意构造', '', '', '', '', '', '备注行']);
  addRow(worksheet, ['', '', '合计', '', '', '', '', 593, '合计行']);
  return workbook;
}

function normalizeZipEntryTimestamps(buffer: Buffer): void {
  const endOfCentralDirectorySignature = 0x06054b50;
  const centralDirectorySignature = 0x02014b50;
  const localFileSignature = 0x04034b50;
  const minimumEndRecordSize = 22;
  const earliestEndRecord = Math.max(0, buffer.length - 65_535 - minimumEndRecordSize);
  let endRecordOffset = -1;

  for (
    let offset = buffer.length - minimumEndRecordSize;
    offset >= earliestEndRecord;
    offset -= 1
  ) {
    if (buffer.readUInt32LE(offset) === endOfCentralDirectorySignature) {
      endRecordOffset = offset;
      break;
    }
  }
  if (endRecordOffset < 0) throw new Error('生成的工作簿缺少 ZIP 目录记录。');

  const centralDirectorySize = buffer.readUInt32LE(endRecordOffset + 12);
  const centralDirectoryOffset = buffer.readUInt32LE(endRecordOffset + 16);
  const centralDirectoryEnd = centralDirectoryOffset + centralDirectorySize;
  let entryOffset = centralDirectoryOffset;

  while (entryOffset < centralDirectoryEnd) {
    if (buffer.readUInt32LE(entryOffset) !== centralDirectorySignature) {
      throw new Error('生成的工作簿 ZIP 目录无效。');
    }
    buffer.writeUInt16LE(FIXED_DOS_TIME, entryOffset + 12);
    buffer.writeUInt16LE(FIXED_DOS_DATE, entryOffset + 14);

    const localHeaderOffset = buffer.readUInt32LE(entryOffset + 42);
    if (buffer.readUInt32LE(localHeaderOffset) !== localFileSignature) {
      throw new Error('生成的工作簿 ZIP 本地记录无效。');
    }
    buffer.writeUInt16LE(FIXED_DOS_TIME, localHeaderOffset + 10);
    buffer.writeUInt16LE(FIXED_DOS_DATE, localHeaderOffset + 12);

    const fileNameLength = buffer.readUInt16LE(entryOffset + 28);
    const extraFieldLength = buffer.readUInt16LE(entryOffset + 30);
    const commentLength = buffer.readUInt16LE(entryOffset + 32);
    entryOffset += 46 + fileNameLength + extraFieldLength + commentLength;
  }
}

async function saveWorkbook(workbook: ExcelJS.Workbook, fileName: string): Promise<void> {
  const output = Buffer.from(
    await workbook.xlsx.writeBuffer({
      useSharedStrings: true,
      useStyles: true,
      zip: { compression: 'DEFLATE', compressionOptions: { level: 9 } },
    }),
  );
  normalizeZipEntryTimestamps(output);
  await Promise.all(
    [EXAMPLES_DIRECTORY, PUBLIC_SAMPLES_DIRECTORY].map((directory) =>
      writeFile(path.join(directory, fileName), output),
    ),
  );
}

async function main(): Promise<void> {
  await Promise.all([
    mkdir(EXAMPLES_DIRECTORY, { recursive: true }),
    mkdir(PUBLIC_SAMPLES_DIRECTORY, { recursive: true }),
  ]);
  await Promise.all([
    saveWorkbook(createCleanSample(), 'boq-clean-sample.xlsx'),
    saveWorkbook(createRiskSample(), 'boq-risk-sample.xlsx'),
  ]);
  console.info('Generated reproducible clean and risk samples in examples/ and public/samples/.');
}

await main();
